server:
  port: 8082
  servlet:
    context-path: /

# db
jdbc:
  time:
    driverClass: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/timeworx?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    user: root
    password: a1118zry
  # 初始化连接池中的连接数，取值应在minPoolSize与maxPoolSize之间，默认为3
  initialPoolSize: 5
  # 最大空闲时间，60秒内未使用则连接被丢弃。若为0则永不丢弃。默认值: 0
  maxIdleTime: 60
  # 连接池中保留的最大连接数。默认值: 15
  maxPoolSize: 15
  # 连接池中保留的最小连接数，默认为：3
  minPoolSize: 5
  # 当连接池连接耗尽时，客户端调用getConnection()后等待获取新连接的时间，超时后将抛出SQLException，如设为0则无限期等待。单位毫秒。默认: 0
  checkoutTimeout: 5000
  # 当连接池中的连接耗尽的时候c3p0一次同时获取的连接数。默认值: 3
  acquireIncrement: 5
  # 定义在从数据库获取新连接失败后重复尝试的次数。默认值: 30 ；小于等于0表示无限次
  acquireRetryAttempts: 10
  # 重新尝试的时间间隔，默认为：1000毫秒
  acquireRetryDelay: 1000
  # 每120秒检查所有连接池中的空闲连接。默认值: 0，不检查
  idleConnectionTestPeriod: 120


spring:
  # redis 默认配置
  redis:
    database: 0   # Redis数据库索引
#    password: test123456   # redis哨兵密码
    password: 1307@Jjfa   # redis集群密码
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
    # Redis单机单实例
    host: 127.0.0.1
    port: 6379
    # Redis哨兵模式
#    sentinel:
#      master: aiyx01 #哨兵的名字 #下面是所有哨兵集群节点
#      nodes: 172.31.4.20:8505,172.31.4.20:8506
#    cluster:
#      nodes:
#        #地址要和redis配置中bind地址一致
#        - 172.31.234.128:7000
#        - 172.31.234.128:7001
#        - 172.31.234.131:7000
#        - 172.31.234.131:7001
#        - 172.31.234.146:7000
#        - 172.31.234.146:7001